# pytest.ini
[pytest]
addopts = --headed -n auto --browser=chromium --html=reports/report.html --self-contained-html
testpaths = tests
python_files = test_*.py
python_functions = test_*
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
