# pytest.ini
[pytest]
addopts = --headed --browser=chromium --alluredir allure-results
# addopts = --headed -n auto --browser chromium  --html=reports/report.html --self-contained-html
testpaths = tests
python_files = tests/Scenario/*.py
# python_files = tests/SearchCases/*.py
python_functions = test_*
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
